# Generated by Django 5.2.1 on 2025-06-04 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('area', models.CharField(max_length=50)),
                ('carga_horaria', models.PositiveIntegerField()),
                ('modalidade', models.CharField(max_length=50)),
                ('vagas', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_interessado', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('cidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('como_conheceu', models.CharField(max_length=50)),
                ('data_interesse', models.DateTimeField(auto_now_add=True)),
                ('status_contato', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interessados', to='cursos.curso')),
            ],
        ),
    ]
